Implement Sign in / Sign up
BinaryStudioAcademy/bsa-winter-2021-dbgravy pull request #18
Opened 2021-03-07 13:41 UTC by shrederr

2021-03-07 16:27 UTC, uliana-lobanova requested changes
Also use SCSS instead of SASS. Please rewrite all .sass files into .scss

2021-03-07 16:27 UTC, uliana-lobanova commented on frontend/src/components/InputField/InputField.tsx
> +const InputField = ({
You forgot to set a type. `const InputField: React.FC(or FunctionComponent)<IProps>`
Also, the name of the file should be index.tsx

2021-03-07 16:27 UTC, uliana-lobanova commented on frontend/src/containers/Routing/index.tsx
> +  });
You need to send the second param to this useEffect - when do you need to call it? Now it will be called with each rerender

2021-03-07 16:27 UTC, uliana-lobanova commented on frontend/src/scenes/Auth/sagas/index.ts
> +    if (error.message.includes('duplicate key value')) {
That's an unreliable strategy. What if PostgreSQL is localized and will return errors in a different language? For these reasons we should send CustomError from server with a proper `errorCode`. Error code should be enum. Then you'll be able to check error by its errorCode correctly.

2021-03-09 08:09 UTC, AlikRakhmonov requested changes

2021-03-09 08:09 UTC, AlikRakhmonov commented on frontend/src/common/enums/Routes.ts
> +  SignIn = '/auth/signIn',
sign-up
sign-in

2021-03-09 08:09 UTC, AlikRakhmonov commented on frontend/src/components/InputField/InputField.tsx
> +import React from 'react';
rename file to index.tsx

2021-03-09 08:09 UTC, AlikRakhmonov commented on frontend/src/common/models/auth/IRegister.User.ts
> +export interface IRegisterUser {
remove dot in the middle of the file name

2021-03-09 08:09 UTC, AlikRakhmonov commented on frontend/src/scenes/Auth/components/SignUp/SignUp.tsx
> +import React, { FunctionComponent } from 'react';
rename file to index.tsx

all component main files must be index.tsx

2021-03-09 14:06 UTC, uliana-lobanova requested changes

2021-03-09 14:06 UTC, uliana-lobanova commented on frontend/src/common/models/formik/ValidationSchemas.ts
> +  lastname,
Here should be camel case - firstName, lastName

2021-03-09 14:06 UTC, uliana-lobanova commented on frontend/src/containers/Routing/index.tsx
> +  }, []);
We don't need that. A user should be logged out with the next request to the server after getting Unauthorized error

2021-03-09 14:06 UTC, uliana-lobanova commented on frontend/src/services/authService.tsx
> +type ServerResponse = IAuthServerResponse & Response;
Api helper's methods return only data, without other response object data. So remove redundant ServerResponse type and use IAuthServerResponse interface instead

2021-03-09 14:16 UTC, uliana-lobanova approved these changes

2021-03-09 14:17 UTC, merged