Feature/app repository
BinaryStudioAcademy/bsa-winter-2021-dbgravy pull request #23
Opened 2021-03-08 13:08 UTC by baron1xxx

2021-03-08 15:47 UTC, uliana-lobanova requested changes
Also:
1) Set the return type for all your service functions and make sure you return the data exactly of that type. Currently, you return a lot of redundant columns to the client
2) No need to wrap your service functions into `try...catch` expression. All errors should be caught in the errorHandlerMiddleware

2021-03-08 15:47 UTC, uliana-lobanova commented on backend/src/services/applicationService.ts
> +export const addApp = async ({ name, organizationId, updatedByUserId }: any) => {
get rid of any

2021-03-08 15:47 UTC, uliana-lobanova commented on backend/src/services/applicationService.ts
> +    const app = await getCustomRepository(ApplicationRepository).getAppByName(name);
We need to check not only by name but also by user's currentOrganizationId. Two different organizations can have apps with the same name. You can get user's info from `req.user`

2021-03-08 15:47 UTC, uliana-lobanova commented on backend/src/data/repositories/applicationRepository.ts
> +    return this.find({ relations: ['organization', 'updatedByUser'] });
you need to get all apps of user's current organization, not just all apps

2021-03-09 08:13 UTC, AlikRakhmonov approved these changes

2021-03-09 10:21 UTC, uliana-lobanova approved these changes

2021-03-09 10:21 UTC, merged